Controllers/CrawlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Text;
using SpidySense.Data;

using HtmlAgilityPack;
using Fizzler.Systems.HtmlAgilityPack;

namespace SpidySense.Controllers
{
    public class CrawlerController : Controller
    {
        SSEntities db = new SSEntities();

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.WebUrls = db.WebUrls.OrderBy(wu => wu.Website.Name).OrderBy(wu => wu.Name).ToList();
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Spidy Sense</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Spidy Sense", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Dashboard", "Index", "Home")</li>
                    <li>@Html.ActionLink("Web Crawler", "Index", "Crawler")</li>
                    <li>@Html.ActionLink("Websites", "Index", "Websites")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <h3 class="title">@ViewBag.Title</h3>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>